# Generated by Django 3.2.4 on 2021-06-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210620_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='size_fluid_once',
            new_name='size_fluid_ounce',
        ),
    ]
