# Generated by Django 3.2.4 on 2021-06-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergyproducts',
            old_name='allergy',
            new_name='allergy_id',
        ),
        migrations.RenameField(
            model_name='allergyproducts',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='caffeine',
            new_name='caffeine_mg',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='one_serving',
            new_name='one_serving_kcal',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='protein',
            new_name='protein_g',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='saturated_fat',
            new_name='saturated_fat_g',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='size',
            new_name='size_fluid_ounce',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='size_fluid',
            new_name='size_ml',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='sodium',
            new_name='sodium_mg',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='sugars',
            new_name='sugars_g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='kor_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nutrition',
            new_name='nutrition_id',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
