# Generated by Django 3.2.4 on 2021-06-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210618_0450'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
